### ISSUE TITLE
jar包呢

### ISSUE THREAD

**Issue by jacky8466** [xiaour/SpringBootDemo#1]
![image](https://user-images.githubusercontent.com/11418894/31654959-17e7965a-b35a-11e7-8929-5ca42c9e26f6.png)

**Comment by materone** [comment]
Get rid of the class, and add the Mybatis config in application.yml ..... 
# MyBatis
mybatis:
    typeAliasesPackage: com.xiaour.spring.boot.entity
    mapperLocations: classpath*:/com/xiaour/spring/boot/mapper/*.xml
    configLocation: classpath:mybatis-config.xml

**Comment by HankeOne** [comment]
![lost_jar](https://user-images.githubusercontent.com/32596033/31851734-3a2ce99e-b69e-11e7-8b59-e10be58de02d.jpg)
is this a native jar "dingtalk"  ? 
please help me.

**Comment by HankeOne** [comment]
https://github.com/ddtalk/HarleyCorp 
![image](https://user-images.githubusercontent.com/32596033/31852453-84ab51c0-b6aa-11e7-97ce-a6a58fbe7e29.png)
"dingtalk" 就是指“钉钉”，这个是钉钉的jar包。按照我上面的方式，下载下来，在 "WebContent\WEB-INF\lib" 目录下有你想要的 jar 包

**Comment by xiaour** [comment]
这部分代码在git中已经删除掉了，让很多网友产生误会实在不好意思，可以clone新的代码到本地，所有的jar都可以从maven仓库down下来的
