### ISSUE TITLE
Invalid bound statement (not found)报错

### ISSUE THREAD

**Issue by ZZZJane** [xiaour/SpringBootDemo#13]
您好，运行SpringBootDemo的getUser/{id}这里报错:Invalid bound statement (not found)，查了网上说是mapper下的xml文件没有打包，但是我检查了路径配置都没问题，而且target里有这个xml文件。代码都没有动过，请问怎么解决这个问题？新手有些懵。期待回复，谢谢！

**Comment by ZZZJane** [comment]
解决了问题，xml文件和接口文件的包名没有一一对应。还是想问一下作者大大，为什么您的项目没有一一对应但是不报错呢？是在哪里配置了吗？

**Comment by xiaour** [comment]
如果配置了全局的@MapperScan的路径就没有问题。
