### ISSUE TITLE
is this a native jar "dingtalk" ?

### ISSUE THREAD

**Issue by HankeOne** [xiaour/SpringBootDemo#2]
![lost_jar](https://user-images.githubusercontent.com/32596033/31851766-35606cb4-b69f-11e7-8971-40c5a9e78b92.jpg)

please help me.

**Comment by HankeOne** [comment]
老铁，你确定这个jar包 “dingtalk” 不是一个你本地的jar吗？怎么克隆下来没有呢？

**Comment by xiaour** [comment]
现在dingtalk这部分已经去掉了，这个是为了接入钉钉api的部分，可以clone新的代码到本地

**Comment by xieshuang** [comment]
并没有，我刚拉了一下，还是这样的老铁
