### ISSUE TITLE
纯后台代码？没有页面，怎么玩。。

### ISSUE THREAD

**Issue by Dwannn** [xiaour/SpringBootDemo#3]
DataBaseConfiguration 类
import org.springframework.core.env.Environment; 报错

**Comment by xiaour** [comment]
是的，这是一个纯后端代码的，没有页面，因为现在大家多数使用的是前后端分离的模式。

**Comment by wrrgit** [comment]
博主，怎么验证注册登录啊？

**Comment by xiaour** [comment]
注册登录没有关系，如果需要加Filter或者使用其他框架，直接引入相关的包或者类就可以了
