### ISSUE TITLE
No route info of this topic, PushTopic

### ISSUE THREAD

**Issue by zhangchao778** [xiaour/SpringBootDemo#9]
为什么我发送消息报错 No route info of this topic, PushTopic

**Comment by xiaour** [comment]
在启动mqbroker的时候需要指定autoCreateTopicEnable=true。
例如：
nohup sh mqbroker -n 127.0.0.1:9876 autoCreateTopicEnable=true > ~/logs/rocketmqlogs/broker.log 2>&1 &
